/*
 * =====================================================================================
 *
 *       Filename:  1113.c
 *
 *    Description:  
 *    Problem Description
 *    A simple mathematical formula for e is
 *    where n is allowed to go to infinity. This can actually yield very accurate approximations of e using relatively small values of n.
 *    Output
 *    Output the approximations of e generated by the above formula for the values of n from 0 to 9. The beginning of your output should appear similar to that shown below.
 *    Sample Output
 *    n e
 *    - -----------
 *    0 1
 *    1 2
 *    2 2.5
 *    3 2.666666667
 *    4 2.708333333
 *
 *        Created:  04/25/2014 22:05:56
 *       Compiler:  gcc
 *
 *         Author:  Jackie Kuo (http://jackiekuo.com), j.kuo2012@gmail.com
 *
 * =====================================================================================
 */

#include <stdio.h>
int factorial(int n){
	int i,f;
	for(i=f=1;i<=n;i++)
		f*=i;
	return f;
}
int main(){
	double e;
	int n,i;
	printf("n e\n- -----------\n0 1\n1 2\n2 2.5\n");
	for(n=3;n<10;n++){
		for(i=0,e=0.0;i<=n;i++)
			e+=(double)1/factorial(i);
		printf("%d %.9lf\n",n,e);
	}
	return 0;
}
