/*
 * =====================================================================================
 *
 *       Filename:  5007.c
 *
 *    Description:  
 *    After observation, you found words “Apple” appear everywhere in his posts. After your counting, you concluded that “Apple”, “iPhone”, “iPod”, “iPad” are the most high-frequency words in his blog. Once one of these words were read by your smart script, it will make a comment “MAI MAI MAI!”, and go on reading the post.
 *    In order to make it more funny, you, as a fan of Sony, also want to make some comments about Sony. So you want to add a new rule to the script: make a comment “SONY DAFA IS GOOD!” when “Sony” appears.
 *    Input
 *    A blog article described above, which contains only printable characters(whose ASCII code is between 32 and 127), CR(ASCII code 13, ‘\r’ in C/C++), LF(ASCII code 10, ‘\n’ in C/C++), please process input until EOF. Note all characters are case sensitive.
 *    The size of the article does not exceed 8KB.
 *    Output
 *    Output should contains comments generated by your script, one per line.
 *    Sample Input
 *    Apple bananaiPad lemon ApplepiSony 233 Tim cook is doubi from Apple iPhoneipad iPhone30 is so biiiiiiig Microsoft makes good App.
 *    Sample Output
 *    MAI MAI MAI! MAI MAI MAI! MAI MAI MAI! SONY DAFA IS GOOD! MAI MAI MAI! MAI MAI MAI! MAI MAI MAI!
 *
 *        Created:  03/03/2015 19:57:53
 *       Compiler:  gcc
 *
 *         Author:  Jackie Kuo (http://jackiekuo.com), j.kuo2012@gmail.com
 *
 * =====================================================================================
 */

#include <stdio.h>
#include <string.h>
char str[70000],word[7];
long i,j,len;
int main(){
	while(gets(str)){
		for(i=0,len=strlen(str);i<len;++i){
			if(str[i]=='A'&&i<len-4){
				for(j=0;j<5;++j)
					word[j]=str[i+j];
				word[j]='\0';
				if(!strcmp(word,"Apple")){
					printf("MAI MAI MAI!\n");
					i+=j-1;
				}
			}
			else if(str[i]=='i'&&i<len-3){
				for(j=0;j<4;++j)
					word[j]=str[i+j];
				word[j]='\0';
				if(!strcmp(word,"iPad")||!strcmp(word,"iPod")){
					printf("MAI MAI MAI!\n");
					i+=j-1;
				}
				else if(i<len-5){
					word[j]=str[i+j];
					word[j+1]=str[i+j+1];
					word[j+2]='\0';
					if(!strcmp(word,"iPhone")){
						printf("MAI MAI MAI!\n");
						i+=j;
					}
				}
			}
			else if(str[i]=='S'&&i<len-3){
				for(j=0;j<4;++j)
					word[j]=str[i+j];
				word[j]='\0';
				if(!strcmp(word,"Sony")){
					printf("SONY DAFA IS GOOD!\n");
					i+=j-1;
				}
			}
		}
	}
	return 0;
}
